import type { Metadata } from "next";
import { Inter, Poppins } from "next/font/google";
import "./globals.css";
import { QueryProvider } from "@/provider/query_provider";
import { Toaster } from "sonner";
import { UserProvider } from "@/context/user";
import Providers from "@/provider/bprogress_provider";

const interSans = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

const poppins = Poppins({
  weight: ["400", "700"],
  subsets: ["latin"],
  variable: "--font-poppins",
});

export const metadata: Metadata = {
  title: "LetWatch",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${interSans.variable} ${poppins.variable} antialiased bg-black`}
      >
        <Providers>
          <UserProvider>
            <QueryProvider>
              <div>{children}</div>
              <Toaster richColors duration={3500} position="top-right" />
            </QueryProvider>
          </UserProvider>
        </Providers>
      </body>
    </html>
  );
}
